### ISSUE TITLE
Why not ship Minima with Normalize.css?

### ISSUE THREAD

**Issue by ghost** [shreyasminocha/Minima#1]

**Comment by shreyasminocha** [comment]
Hi Andrey, that's a great idea! However, including all of Normalize will go against Minima's principles of minimalism. Instead, I'm planning to include a modified version of Normalize that includes only the relevant styles.

**Comment by shreyasminocha** [comment]
Commit [f37514d](https://github.com/shreyasminocha/Minima/commit/f37514d087c989a938b4aea28fbe7ae21a406d71) resolves this issue. Closing.

**Comment by ghost** [comment]
Thank you :D
